package core

enum TagType {
    ZONE, SIDE, TYPE,
    NAME,
    MANA, NATIVE_MANA,
    ATTACK, NATIVE_ATTACK,
    HEALTH, MAX_HEALTH, NATIVE_HEALTH,
    PENDING_DESTROY,
    ARMOR,
    RACE,
    DURABILITY
}